identifier_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 40
    error: 50
type_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 50
    error: 70
function_body_length:
  warning: 125
  error: 200
file_length:
  warning: 1250
  error: 2000
type_body_length:
  warning: 1000
  error: 2000
cyclomatic_complexity:
  ignores_case_statements: true
  warning: 13
  error: 15
large_tuple:
  warning: 4
  error: 6
disabled_rules:
  - void_function_in_ternary